In [3]:
import numpy as np

In [6]:
arr=np.array([[ 1, 2, 3],
              [ 4, 2, 5]])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr.ndim

2

In [9]:
arr.shape

(2, 3)

In [10]:
arr.size

6

In [11]:
arr.dtype

dtype('int32')

In [13]:
 a=np.array([[1, 2, 4],[5, 7, 8]], dtype= 'float')
print(a)

[[1. 2. 4.]
 [5. 7. 8.]]


In [14]:
c=np.ones((3,4))

In [15]:
print(c)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [18]:
np.arange(0,30,5)

array([ 0,  5, 10, 15, 20, 25])

In [19]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [20]:
np.random.random((2,2))

array([[0.07147073, 0.3677289 ],
       [0.46699671, 0.16820745]])

In [24]:
arr=np.array([[1,2,3,4],
              [4,5,6,8],
              [7,8,9,1]])
newarr=arr.reshape(2,2,3)

In [25]:
newarr

array([[[1, 2, 3],
        [4, 4, 5]],

       [[6, 8, 7],
        [8, 9, 1]]])